# Generated by Django 3.2.12 on 2022-04-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_city_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
