# Generated by Django 3.2.12 on 2022-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_city_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
