# Generated by Django 3.2.12 on 2022-04-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
