# Generated by Django 3.2.12 on 2022-04-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_city_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='date',
        ),
    ]
